# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-12-07 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('planeID', models.CharField(default='null', max_length=256)),
                ('RTdata', models.FloatField()),
                ('SSdata', models.FloatField()),
                ('TLDdata', models.CharField(default='null', max_length=256)),
                ('owner', models.CharField(default='null', max_length=256)),
            ],
        ),
    ]
